APP_NAME="Centro de Mando Cancún"
APP_ENV=local
APP_KEY=base64:knPTWQfTeTOXysK/TfgCYjE5K06q3t9TG2Y+YLnKg2w=
APP_DEBUG=true
APP_URL=http://localhost

APP_LOCALE=es
APP_TIMEZONE=America/Cancun
APP_FALLBACK_LOCALE=es
APP_FAKER_LOCALE=es_MX

DB_CONNECTION=pgsql
DB_HOST=127.0.0.1
DB_PORT=5432
DB_DATABASE=cc_implan
DB_USERNAME=postgres
DB_PASSWORD=1969

CACHE_STORE=file
